"""empty message

Revision ID: 0abb93d6b9f5
Revises: d08bda3a6b4a
Create Date: 2026-05-06 14:13:05.672019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abb93d6b9f5'
down_revision = 'd08bda3a6b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('max_members')

    # ### end Alembic commands ###
