"""empty message

Revision ID: 1736d6d3c6e4
Revises: 7057b7da1012
Create Date: 2026-05-06 16:33:54.391976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1736d6d3c6e4'
down_revision = '7057b7da1012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_trajectories_timestamp'))
        batch_op.create_index(batch_op.f('ix_trajectories_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_foreign_key('fk_trajectories_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_trajectories_group_id', 'groups', ['group_id'], ['id'])
        batch_op.drop_column('speed')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('altitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trajectories_recored_at'))
        batch_op.create_index(batch_op.f('ix_trajectories_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('recored_at')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
