"""empty message

Revision ID: 7057b7da1012
Revises: 0abb93d6b9f5
Create Date: 2026-05-06 15:47:59.502930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7057b7da1012'
down_revision = '0abb93d6b9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('room_nickname', sa.String(length=80), nullable=False))
        batch_op.drop_column('place_name')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('place_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('room_nickname')
        batch_op.drop_column('visited_at')

    # ### end Alembic commands ###
