"""empty message

Revision ID: e471691409dc
Revises: c8afb302fa56
Create Date: 2026-05-04 17:42:06.548219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e471691409dc'
down_revision = 'c8afb302fa56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trajectories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trajectories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trajectories_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trajectories_timestamp'))

    op.drop_table('trajectories')
    # ### end Alembic commands ###
